---
- name: Update LCD message
  ansible.builtin.import_role:
    name: lcd-update
  vars:
    lcd_message: "Disable apparmor"

- name: Disable apparmor (1)
  ansible.builtin.command:
    cmd: ln -s /etc/apparmor.d/usr.sbin.libvirtd /etc/apparmor.d/disable/
  ignore_errors: true

- name: Disable apparmor (2)
  ansible.builtin.command:
    cmd: ln -s /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper /etc/apparmor.d/disable/
  ignore_errors: true

- name: Disable apparmor (3)
  ansible.builtin.command:
    cmd: apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
  ignore_errors: true

- name: Disable apparmor (4)
  ansible.builtin.command:
    cmd: apparmor_parser -R /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
  ignore_errors: true
