---
- name: Update LCD message
  ansible.builtin.import_role:
    name: lcd-update
  vars:
    lcd_message: "Setting up cluster"

- name: Read setup-config.yml content
  ansible.builtin.slurp:
    src: /etc/kthcloud/config.yml
  register: config_content

- name: Decode setup-config.yml content from base64
  ansible.builtin.set_fact:
    config: "{{ config_content.content | b64decode | from_yaml }}"

- name: Set up K3s cluster node
  include_tasks: setup_k3s_cluster_node.yml
  when: config.clusterType == 'k3s'

- name: Set up Rancher cluster node
  include_tasks: setup_rancher_node.yml
  when: config.clusterType == 'rancher'






