- name: Copy script from templates
  ansible.builtin.copy:
    src: "{{ templates_path }}/connect_rancher_cluster_node.py"
    dest: /usr/bin/kthcloud-connect
    owner: root
    group: root
    mode: 0755

- name: Install Rancher client python package
  ansible.builtin.pip:
    name: git+https://github.com/rancher/client-python.git@master

- name: Run connect script
  command: /usr/bin/kthcloud-connect