---
- name: Update LCD message
  ansible.builtin.import_role:
    name: lcd-update
  vars:
    lcd_message: "Configuring libvirt"

- name: Configure qemu vnc address
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: "^vnc_listen"
    line: vnc_listen = "0.0.0.0"
    owner: root
    group: root
    mode: "0644"

- name: Configure libvirtd_opts
  ansible.builtin.lineinfile:
    path: /etc/default/libvirtd
    regexp: "^LIBVIRTD_ARGS"
    line: LIBVIRTD_ARGS="--listen"
    owner: root
    group: root
    mode: "0644"

- name: Configure libvirtd_opts
  ansible.builtin.lineinfile:
    path: /etc/default/libvirtd
    regexp: "^libvirtd_opts"
    line: libvirtd_opts="-l"
    owner: root
    group: root
    mode: "0644"

- name: Configure libvirtd.opts listen_tls
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^listen_tls"
    line: listen_tls=0
    owner: root
    group: root
    mode: "0644"

- name: Configure libvirtd.opts listen_tcp
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^listen_tcp"
    line: listen_tcp=1
    owner: root
    group: root
    mode: "0644"

- name: Configure libvirtd.opts tcp_port
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^tcp_port"
    line: tcp_port="16509"
    owner: root
    group: root
    mode: "0644"

- name: Configure libvirtd.opts mdns_adv
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^mdns_adv"
    line: mdns_adv=0
    owner: root
    group: root
    mode: "0644"

- name: Configure libvirtd.opts auth_tcp
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirtd.conf
    regexp: "^auth_tcp"
    line: auth_tcp="none"
    owner: root
    group: root
    mode: "0644"

- name: Mask libvirtd.socket
  ansible.builtin.systemd:
    name: libvirtd.socket
    masked: yes

- name: Mask libvirtd-ro.socket
  ansible.builtin.systemd:
    name: libvirtd-ro.socket
    masked: yes

- name: Mask libvirtd-admin.socket
  ansible.builtin.systemd:
    name: libvirtd-admin.socket
    masked: yes

- name: Mask libvirtd-tls.socket
  ansible.builtin.systemd:
    name: libvirtd-tls.socket
    masked: yes

- name: Mask libvirtd-tcp.socket
  ansible.builtin.systemd:
    name: libvirtd-tcp.socket
    masked: yes

- name: Restart service libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: restarted
