---
- name: "Ensure PCIe virtualization"
  debug:
    msg: "Please ensure PCIe virtualization is enabled in BIOS before this step"

- name: "Install dependencies"
  apt:
    name:
      [
        qemu-utils,
        libvirt-daemon-system,
        libvirt-clients,
        bridge-utils,
        virt-manager,
        ovmf,
      ]
    state: latest
    update_cache: yes
  when: requires_configuration

- name: "Install non-passthrough dependencies"
  apt:
    name:
      [
        nvidia-driver-550-server,
        nvidia-utils-550-server
      ]
    state: latest
    update_cache: yes
  when: has_non_passthrough