---
- name: Update LCD message
  ansible.builtin.import_role:
    name: lcd-update
  vars:
    lcd_message: "Set timezone to {{ timezone }}"

- name: "Set timezone to {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"
