---
- name: Update LCD message
  ansible.builtin.import_role:
    name: lcd-update
  vars:
    lcd_message: "Configuring kthcloud API"

# install bun as root user https://bun.sh/install, then move it to /usr/local/bin
- name: "Install bun"
  shell: "curl -fsSL https://bun.sh/install | bash"
  remote_user: root

- name: "Move bun to /usr/local/bin"
  shell: mv /home/root/bin/bun /usr/local/bin/bun

- name: "Make bun executable"
  shell: chmod a+x /usr/local/bin/bun

- name: "Delete old host-api folder"
  file:
    path: "{{ apps_install_path }}/host-api"
    state: absent

- name: Clone repo
  ansible.builtin.git:
    repo: "{{ host_api_git_url }}"
    dest: "{{ apps_install_path }}/host-api"

- name: "Make install.sh executable"
  shell: chmod a+x "{{ apps_install_path }}/host-api/install.sh"

- name: "Install host-api"
  shell: "{{ apps_install_path }}/host-api/install.sh {{apps_install_path}}/host-api"