---
- name: Update LCD message
  ansible.builtin.import_role:
    name: lcd-update
  vars:
    lcd_message: "Configuring kthcloud API"

- name: "Install bun"
  ansible.builtin.shell: curl -fsSL https://bun.sh/install | bash

- name: "Move bun to /usr/local/bin"
  ansible.builtin.shell: mv /root/.bun/bin/bun /usr/local/bin/

- name: "Make bun executable"
  ansible.builtin.shell: chmod a+x /usr/local/bin/bun

- name: "Delete old host-api folder"
  file:
    path: "{{ apps_install_path }}/host-api"
    state: absent

- name: Clone repo
  ansible.builtin.git:
    repo: "{{ host_api_git_url }}"
    dest: "{{ apps_install_path }}/host-api"

- name: "Make install.sh executable"
  ansible.builtin.shell: chmod a+x "{{ apps_install_path }}/host-api/install.sh"

- name: "Install host-api"
  ansible.builtin.shell: "{{ apps_install_path }}/host-api/install.sh {{apps_install_path}}/host-api"